# Generated by Django 4.1.7 on 2023-05-23 13:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('client_name', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100, unique=True)),
                ('subscribers', models.ManyToManyField(blank=True, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_date_of_publication', models.DateTimeField(auto_now_add=True)),
                ('article_title', models.CharField(max_length=50, unique=True)),
                ('article_author', models.CharField(max_length=50)),
                ('article_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsPortalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.newsportal')),
                ('news_portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.newscategory')),
            ],
        ),
        migrations.AddField(
            model_name='newsportal',
            name='news_category',
            field=models.ManyToManyField(through='simpleapp.NewsPortalCategory', to='simpleapp.newscategory'),
        ),
    ]
